version:'3'
# to run it use this command docker-compose up or down to close it.

services:
	selenium-hub:
		image: selenium/hub
		ports:
			- "4442-4444:4442-4444"
		networks:
			- grid
			
	node-chrome:
		image: selenium/node-chrome
		environment:
			- SE_EVENT_BUS_HOST=selenium-hub
			- SE_EVENT_BUS_PUBLISH_PORT=4442
			- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
		networks:
			- grid
			
	node-firefox:
		image: selenium/node-firefox
		environment:
			- SE_EVENT_BUS_HOST=selenium-hub
			- SE_EVENT_BUS_PUBLISH_PORT=4442
			- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
		networks:
			- grid
			
networks:
	grid:
		driver: bridge
			